[env]
TERM = "xterm-256color"

[window]
#opacity = 0.9
padding = { x = 20, y = 20 }

[font]
size = 18
offset = { y = 14 }
glyph_offset = { y = 8 }

[cursor]
style = { shape = "Underline", blinking = "Never" }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "Space", mods = "Option", action = "ToggleViMode" },
]

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
