[env]
TERM = "xterm-256color"

[window]
#opacity = 0.9
padding = { x = 20, y = 20 }

[font]
#normal = { family = "BigBlueTerm437 Nerd Font", style = "Regular" }
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 12
offset = { y = 10 }
glyph_offset = { y = 4 }

[cursor]
style = { shape = "Underline", blinking = "Never" }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "Space", mods = "Option", action = "ToggleViMode" },
]

#[general]
#import = [
#  "~/.config/alacritty/catppuccin-macchiato.toml"
#]
