import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 25, y = 25 }

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 12
offset = { y = 10 }
glyph_offset = { y = 4 }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Tab", mods = "Option", action = "SelectNextTab" },
  { key = "Tab", mods = "Option|Shift", action = "SelectPreviousTab" },
]
