import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
padding = { x = 25, y = 25 }

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 14
offset = { y = 12 }
glyph_offset = { y = 6 }

[cursor]
style = { shape = "Underline", blinking = "Never" }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Tab", mods = "Option", action = "SelectNextTab" },
  { key = "Tab", mods = "Option|Shift", action = "SelectPreviousTab" },
  { key = "Space", mods = "Control|Option", action = "ToggleViMode" },
]
