import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
padding = { x = 25, y = 25 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Light Italic" }
size = 14
offset = { y = 10 }
glyph_offset = { y = 4 }

[cursor]
style = { shape = "Underline", blinking = "Never" }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  { key = "Tab", mods = "Option", action = "SelectNextTab" },
  { key = "Tab", mods = "Option|Shift", action = "SelectPreviousTab" },
  { key = "Space", mods = "Option", action = "ToggleViMode" },
]
