import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 25, y = 25 }

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 14
offset = { y = 8 }
glyph_offset = { y = 4 }

[keyboard]
bindings = [
{ key = "Enter", mods = "Command", action = "ToggleFullscreen" }
]
