"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$character"""

add_newline = false

[directory]
style = "bright-black"

[character]
success_symbol = "[\uf054](green)"
error_symbol = "[\uf054](red)"
vimcmd_symbol = "[\ueab5](green)"

[git_branch]
format = "[$branch]($style) "
style = "black"
