"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$character"""

add_newline = false

[directory]
style = "black"

[character]
success_symbol = "[\ueab6](green)"
error_symbol = "[\ueab6](red)"
vimcmd_symbol = "[\ueab5](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"
